Update gem to support the latest Solidus version

diff --git a/bin/sandbox b/bin/sandbox
--- a/bin/sandbox
+++ b/bin/sandbox
@@ -1,41 +1,45 @@
 #!/usr/bin/env bash
 
 set -e
-test -z "${DEBUG+empty_string}" || set -x
 
-test "$DB" = "sqlite" && export DB="sqlite3"
+case "$DB" in
+postgres|postgresql)
+  RAILSDB="postgresql"
+  ;;
+mysql)
+  RAILSDB="mysql"
+  ;;
+sqlite|'')
+  RAILSDB="sqlite3"
+  ;;
+*)
+  echo "Invalid DB specified: $DB"
+  exit 1
+  ;;
+esac
 
-if [ -z "$SOLIDUS_BRANCH" ]
+if [ ! -z $SOLIDUS_BRANCH ]
 then
-  echo "~~> Use 'export SOLIDUS_BRANCH=[main|v3.2|...]' to control the Solidus branch"
-  SOLIDUS_BRANCH="main"
+  BRANCH=$SOLIDUS_BRANCH
+else
+  BRANCH="main"
 fi
-echo "~~> Using branch $SOLIDUS_BRANCH of solidus"
-
-if [ -z "$SOLIDUS_FRONTEND" ]
-then
-  echo "~~> Use 'export SOLIDUS_FRONTEND=[solidus_frontend|solidus_starter_frontend]' to control the Solidus frontend"
-  SOLIDUS_FRONTEND="solidus_frontend"
-fi
-echo "~~> Using branch $SOLIDUS_FRONTEND as the solidus frontend"
 
 extension_name="solidus_reviews"
 
 # Stay away from the bundler env of the containing extension.
 function unbundled {
-  ruby -rbundler -e'b = proc {system *ARGV}; Bundler.respond_to?(:with_unbundled_env) ? Bundler.with_unbundled_env(&b) : Bundler.with_clean_env(&b)' -- $@
+  ruby -rbundler -e'b = proc {system *ARGV}; Bundler.respond_to?(:with_unbundled_env) ? Bundler.with_unbundled_env(&b) : Bundler.with_clean_env(&b)' -- "$@"
 }
 
 rm -rf ./sandbox
-unbundled bundle exec rails new sandbox \
-  --database="${DB:-sqlite3}" \
-  --skip-bundle \
+rails new sandbox \
+  --database="$RAILSDB" \
   --skip-git \
   --skip-keeps \
   --skip-rc \
-  --skip-spring \
-  --skip-test \
-  --skip-javascript
+  --skip-bootsnap \
+  --skip-test
 
 if [ ! -d "sandbox" ]; then
   echo 'sandbox rails application failed'
@@ -43,36 +47,16 @@ if [ ! -d "sandbox" ]; then
 fi
 
 cd ./sandbox
-cat <<RUBY >> Gemfile
-gem 'solidus', github: 'solidusio/solidus', branch: '$SOLIDUS_BRANCH'
-gem 'rails-i18n'
-gem 'solidus_i18n'
-
-gem '$extension_name', path: '..'
-
-group :test, :development do
-  platforms :mri do
-    gem 'pry-byebug'
-  end
-end
-RUBY
-
-unbundled bundle install --gemfile Gemfile
-
+unbundled bundle add solidus --github solidusio/solidus --branch "${BRANCH:-main}" --version '> 0.a'
 unbundled bundle exec rake db:drop db:create
-
-unbundled bundle exec rails generate solidus:install \
-  --auto-accept \
-  --user_class=Spree::User \
-  --enforce_available_locales=true \
-  --with-authentication=true \
-  --payment-method=none \
-  --frontend=${SOLIDUS_FRONTEND} \
-  $@
-
-unbundled bundle exec rails generate solidus:auth:install --auto-run-migrations
-unbundled bundle exec rails generate ${extension_name}:install --auto-run-migrations
+unbundled bundle exec rails generate solidus:install --payment-method=none --auto-accept "$@"
+unbundled bundle add ${extension_name} --path '..'
+unbundled bundle exec rails generate ${extension_name}:install --frontend=starter --auto-run-migrations
+bin/rails assets:precompile
 
 echo
-echo "🚀 Sandbox app successfully created for $extension_name!"
-echo "🧪 This app is intended for test purposes."
+echo "🚀 Sandbox app successfully created for ${extension_name}!"
+echo "🚀 Using $RAILSDB and Solidus $BRANCH"
+echo "🚀 Use 'export DB=[postgres|mysql|sqlite]' to control the DB adapter"
+echo "🚀 Use 'export SOLIDUS_BRANCH=<BRANCH-NAME>' to control the Solidus version"
+echo "🚀 This app is intended for test purposes."
